apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: exchange-pq
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      imagePullSecrets:
        - name: alicr
      containers:
      - name: exchange-pq
        image: registry-vpc.cn-wulanchabu.aliyuncs.com/fluidex-demo/tsdb:2.1.0-pg13
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: prover_db
        # configMap volume
        volumeMounts:
          - name: data-vol
            mountPath: /var/lib/postgresql
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: db-pvc
